// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.PostgresMigrations.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColumnTypeOperator", b =>
                {
                    b.Property<int>("ColumnTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorsId")
                        .HasColumnType("integer");

                    b.HasKey("ColumnTypesId", "OperatorsId");

                    b.HasIndex("OperatorsId");

                    b.ToTable("ColumnTypeOperatorMapping", "search");
                });

            modelBuilder.Entity("Domain.Entities.FileJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("FileJobs");
                });

            modelBuilder.Entity("Domain.Entities.FileJobUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<string>("BatchKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(350)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("varchar(350)");

                    b.Property<int>("FileJobId")
                        .HasColumnType("integer");

                    b.Property<int>("FileRowType")
                        .HasColumnType("integer");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FileJobId", "BatchKey")
                        .IsUnique();

                    b.ToTable("FileJobUploads");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("MainTableId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MainTableId");

                    b.ToTable("AdvancedSearches", "search");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvancedSearchId")
                        .HasColumnType("integer");

                    b.Property<int>("ColumnDefinitionId")
                        .HasColumnType("integer");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdvancedSearchId");

                    b.HasIndex("ColumnDefinitionId");

                    b.ToTable("AdvancedSearchColumns", "search");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchColumnDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ColumnTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColumnTypeId");

                    b.HasIndex("TableId");

                    b.ToTable("AdvancedSearchColumnDefinition");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchJoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvancedSearchId")
                        .HasColumnType("integer");

                    b.Property<int>("FromTableAliasId")
                        .HasColumnType("integer");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("JoinCondition")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ToTableAliasId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvancedSearchId");

                    b.ToTable("AdvancedSearchJoins", "search");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ForeignKeyColumn")
                        .HasColumnType("text");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("ParentKeyColumn")
                        .HasColumnType("text");

                    b.Property<int?>("ParentTableId")
                        .HasColumnType("integer");

                    b.Property<string>("TableAlias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentTableId");

                    b.ToTable("AdvancedSearchTables", "search");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvancedSearchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("JsonDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvancedSearchId");

                    b.ToTable("AdvancedSearchTemplate");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.ColumnType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ColumnTypes", "search");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("InputControl")
                        .HasColumnType("integer");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("SqlTemplate")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ValueMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Operators", "search");
                });

            modelBuilder.Entity("Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<int>("TaskListId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TaskListId", "Title")
                        .IsUnique();

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("Domain.Entities.TaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceFileJobId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("PriorityId");

                    b.ToTable("TaskLists");
                });

            modelBuilder.Entity("Domain.Entities.TaskPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskPriority");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AspId")
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegisterToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisterTokenExpieryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Consumer")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ReceivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox_messages", "messaging");
                });

            modelBuilder.Entity("Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Sequence")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("\"ProcessedOn\" IS NULL");

                    b.ToTable("outbox_messages", "messaging");
                });

            modelBuilder.Entity("ColumnTypeOperator", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.ColumnType", null)
                        .WithMany()
                        .HasForeignKey("ColumnTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SearchEntities.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.FileJobUpload", b =>
                {
                    b.HasOne("Domain.Entities.FileJob", "FileJob")
                        .WithMany("FileJobUploads")
                        .HasForeignKey("FileJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileJob");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearch", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearchTable", "MainTable")
                        .WithMany()
                        .HasForeignKey("MainTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainTable");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchColumn", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearch", "AdvancedSearch")
                        .WithMany("AdvancedSearchColumns")
                        .HasForeignKey("AdvancedSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearchColumnDefinition", "ColumnDefinition")
                        .WithMany()
                        .HasForeignKey("ColumnDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvancedSearch");

                    b.Navigation("ColumnDefinition");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchColumnDefinition", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.ColumnType", "ColumnType")
                        .WithMany()
                        .HasForeignKey("ColumnTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearchTable", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColumnType");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchJoin", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearch", "AdvancedSearch")
                        .WithMany()
                        .HasForeignKey("AdvancedSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvancedSearch");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchTable", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearchTable", "ParentTable")
                        .WithMany()
                        .HasForeignKey("ParentTableId");

                    b.Navigation("ParentTable");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchTemplate", b =>
                {
                    b.HasOne("Domain.Entities.SearchEntities.AdvancedSearch", null)
                        .WithMany("Templates")
                        .HasForeignKey("AdvancedSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Domain.Entities.TaskList", "TaskList")
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("Domain.Entities.TaskList", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedTo")
                        .WithMany("TaskLists")
                        .HasForeignKey("AssignedToId");

                    b.HasOne("Domain.Entities.TaskPriority", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("Domain.Entities.FileJob", b =>
                {
                    b.Navigation("FileJobUploads");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearch", b =>
                {
                    b.Navigation("AdvancedSearchColumns");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Domain.Entities.SearchEntities.AdvancedSearchTable", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Domain.Entities.TaskList", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("Domain.Entities.TaskPriority", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("TaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
