<Project Sdk="Aspire.AppHost.Sdk/13.1.0">
	
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>8e3c181d-62e4-447b-bc42-34cf12a11b96</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.PapercutSmtp" />
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WorkerServiceProcess\WorkerServiceProcess.csproj" />
    <ProjectReference Include="..\WebApiAuth\WebApiAuth.csproj" />
    <ProjectReference Include="..\WebApi\WebApi.csproj" />
    <ProjectReference Include="..\WebsiteApp\WebsiteApp.csproj" />
  </ItemGroup>

</Project>
