<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <UserSecretsId>80f7f48a-a5ac-49d3-a0df-fb7290b47a6e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.Data.Sqlite" />
        <PackageReference Include="Microsoft.Data.Sqlite.Core" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Testcontainers.MsSql" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\Presentation\WebApiAuth\WebApiAuth.csproj" />
        <ProjectReference Include="..\SharedTestDataLibrary\SharedTestDataLibrary.csproj" />
        <ProjectReference Include="..\SharedUtilityTestMethods\SharedUtilityTestMethods.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
