<Project Sdk="Microsoft.NET.Sdk.Web">



  <PropertyGroup>
    <UserSecretsId>143d5000-3cba-4cf4-bd9a-ef3487480d43</UserSecretsId>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="Hangfire" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="System.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TaskMaster.ServiceDefaults\TaskMaster.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
